apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-metrics
  labels:
    app: redis
    release: prometheus
spec:
  selector:
    matchLabels:
      app: redis
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      targetPort: 9121
  namespaceSelector:
    matchNames:
      - infra