apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-minimal-config
  namespace: istio-system
data:
  values.yaml: |
    pilot:
      autoscaleEnabled: false
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    
    telemetry:
      enabled: false
    
    ingressGateways:
      istio-ingressgateway:
        autoscaleEnabled: false
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi