apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: tracing
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3200
    targetPort: 3200
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
  - name: grpc
    port: 9095
    targetPort: 9095
  selector:
    app: tempo