apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-dev-config
  namespace: istio-system
data:
  values.yaml: |
    global:
      logging:
        level: "default:debug"
    
    pilot:
      autoscaleEnabled: true
      autoscaleMin: 1
      autoscaleMax: 3
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 1024Mi
    
    telemetry:
      enabled: true
      v2:
        prometheus:
          configOverride:
            inboundSidecar:
              disable_host_header_fallback: true
            outboundSidecar:
              disable_host_header_fallback: true
    
    ingressGateways:
      istio-ingressgateway:
        autoscaleEnabled: true
        autoscaleMin: 1
        autoscaleMax: 3