apiVersion: v1
kind: Service
metadata:
  name: postgres-metrics
  namespace: infra
  labels:
    app: postgres
    component: metrics
spec:
  type: NodePort
  ports:
  - port: 9187
    targetPort: 9187
    nodePort: 30187
    name: metrics
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: redis-metrics
  namespace: infra
  labels:
    app: redis
    component: metrics
spec:
  type: NodePort
  ports:
  - port: 9121
    targetPort: 9121
    nodePort: 30121
    name: metrics
  selector:
    app: redis