apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: infra
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: postgres
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        env:
        - name: POSTGRES_MAX_CONNECTIONS
          value: "100"
        - name: POSTGRES_SHARED_BUFFERS
          value: "256MB"
        - name: POSTGRES_EFFECTIVE_CACHE_SIZE
          value: "1GB"
        - name: POSTGRES_WORK_MEM
          value: "4MB"
        - name: POSTGRES_MAINTENANCE_WORK_MEM
          value: "64MB"
      - name: postgres-exporter
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: infra
spec:
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi