apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
  labels:
    app: curl-pod
spec:
  containers:
  - name: curl
    image: curlimages/curl:latest
    command: ["sleep", "3600"]
  restartPolicy: Never